### ISSUE TITLE
Header issues "To-Do"

### ISSUE THREAD

**Issue by skelrilod** [camelias-residencial/produtos-servicos#6]
- [x] Hyper Link Camelias img - href="/" (homepage)
- [x] Cursor 
- [x] Opacity on hover
- [x] Responsive Search-bar width
- [x] Improve search icon smoothness

--------------------------------

- [x] Setup colors (Same as _breakpoints) -> Figure all colors

- [ ] Modal
